### ISSUE TITLE
favicon.ico is not accessible

### ISSUE THREAD

**Issue by sadovnikov** [ContainerSolutions/minimesos.org#13]
Openning https://minimesos.org/ in brower gives `https://minimesos.org/favicon.ico Failed to load resource: the server responded with a status of 403 (Forbidden)`

**Comment by sadovnikov** [comment]
@adam-sandor, @frankscholten for your attention

**Comment by adam-sandor** [comment]
Thanks Victor, can you try to load the page from an incognito browser window? I don't see any favicon request right now from the browser (which might be an issue in itself)

**Comment by sadovnikov** [comment]
The problem is with both HTTP and HTTPS, in normal and incognito modes

![image](https://cloud.githubusercontent.com/assets/4749332/15390485/4f17265c-1dbc-11e6-85bd-7f2d5fbe49dd.png)

**Comment by adam-sandor** [comment]
Looks like Chrome is the culprit here, it's requesting a favicon even though none is defined in index.html. I guess the best fix will be to actually create a favicon :)
